In [1]:
import numpy as np

In [ ]:
np.__version__

'2.0.2'

In [ ]:
a = np.array([1,2,3,4,5])
a


array([1, 2, 3, 4, 5])

In [ ]:
a[1] = 7
print(a)

[1 7 3 4 5]


In [ ]:
b = np.array (["Paris", "London", "Australia"])
b

array(['Paris', 'London', 'Australia'], dtype='<U9')

In [ ]:
b[0] = 2
print(b)

['2' 'London' 'Australia']


In [ ]:
c = np.array([1,"London",3.5])
c

array(['1', 'London', '3.5'], dtype='<U32')

In [ ]:
print(a)

[1 2 3 4 5]


In [ ]:
print(b)

['Paris' 'London' 'Australia']


In [ ]:
print(c)

['1' 'London' '3.5']


In [ ]:
a.shape

(5,)

In [ ]:
b.shape

(3,)

In [ ]:
c.shape

(3,)

In [ ]:
a.dtype

dtype('int64')

In [ ]:
b.dtype

dtype('<U9')

In [ ]:
c.dtype

dtype('<U32')

In [ ]:
a.ndim

1

In [ ]:
b.ndim

1

In [ ]:
c.ndim

1

In [ ]:
a.size

5

In [ ]:
b.size

3

In [ ]:
c.size

3

In [ ]:
x1 = np.array ([1,2,3,4])
y1 = np.array ([1,2,3,4])
d = x1*y1
e = x1 + y1
print(d)
print(e)

[ 1  4  9 16]
[2 4 6 8]


In [ ]:
list = [ 1,2,3,4,5]
list1 = np.array ([1,2,3])

In [ ]:
print(list)
print(list1)

[1, 2, 3, 4, 5]
[1 2 3]


In [ ]:
list.append(7)
print(list)

[1, 2, 3, 4, 5, 7, 7, 7, 7]


In [ ]:
#list1.append(7) -- error. cannot use simply append to add elements in numpy array. simple array can use append.
list2 = np.append(list1,[0,6])
print(list2)

[1 2 3 0 6]


In [ ]:
print(list1)

[1 2 3]


In [ ]:
list3 = list1 + np.array([5])
print(list3)

[6 7 8]


In [ ]:
list4 = list1 + np.array([3,3,3])
print(list4)

[4 5 6]


In [ ]:
numarr = np.array([1,2,3,4,5])
#numarr
#print(numarr)
numarr1 = np.append(numarr,('London','Paris'))
print(numarr1)

['1' '2' '3' '4' '5' 'London' 'Paris']


In [ ]:
numarr2 = numarr + np.array([5])
print(numarr2)

[ 6  7  8  9 10]


In [ ]:
f = numarr * numarr
g = numarr + numarr
print(f)
print(g)

[ 1  4  9 16 25]
[ 2  4  6  8 10]


In [ ]:
h = numarr + np.array([1,2,3,4,5])
print(h)

[ 2  4  6  8 10]


In [ ]:
a1 = np.array([1,2,3,4,5])
print (a1)

[1 2 3 4 5]


In [ ]:
b1 = a1+np.array([1])
print(b1)

[2 3 4 5 6]


In [ ]:
c1 = a1 * 2
print(c1)

[ 2  4  6  8 10]


In [ ]:
d1 = a1 + np.array([1,2,2,1,2])
print(d1)

[2 4 5 5 7]


In [2]:
import array
import math
num = array.array('i',[1,2,3,4,5])
for i in num:
  print(math.sqrt(i))
  print()
  print(math.pow(i,2))

1.0

1.0
1.4142135623730951

4.0
1.7320508075688772

9.0
2.0

16.0
2.23606797749979

25.0


In [ ]:
a3 = np.array([2,3,4])
a4 = np.sqrt(a3)
print(a4)

a5 = np.exp(a3)
print(a5)

a6 = np.log(a3)
print(a6)

a7 = np.pow(a3,2)
print(a7)

[1.41421356 1.73205081 2.        ]
[ 7.3890561  20.08553692 54.59815003]
[0.69314718 1.09861229 1.38629436]
[ 4  9 16]


In [ ]:
y = np.array([2,2])
t = np.array([5,3])

yt = np.dot(y,t)
print(yt)

yt1 = y@t
print(yt1)

yt2 = y * t
print(yt2)

yt3 = np.sum(yt2)
print(yt3)

16
16
[10  6]
16


In [ ]:
num1 = np.array([1,2,3,4,5])
num2 = np.sum(num1)
print(num2)

15


# Two Dimensional - 2D array


---





In [ ]:
import array
TwoD = np.array([[1,2,],[3,4]])
print(TwoD.shape)
print(TwoD.ndim)
print(TwoD)

(2, 2)
2
[[1 2]
 [3 4]]


In [ ]:
OneD = np.array([5,6,7])
print(OneD)
print(OneD.shape)

[5 6 7]
(3,)


In [ ]:
print(OneD[1])
print(TwoD[0,0])
print(TwoD[1,1])
print(TwoD[: , 0]) #SLICING -> print entire row at column 0 place
print(TwoD[0, :])  #SLICING -> print entire column at row 0 place
print(TwoD[1,:])
print(TwoD[: , 1])

6
1
4
[1 3]
[1 2]
[3 4]
[2 4]


In [ ]:
x1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
x1.shape

print(x1)
print(x1[2,1]) # print (x1,[R,C])

print(x1[:,1])
print(x1.T) # Transpose -> changing R to C and C to R

[[1 2 3]
 [4 5 6]
 [7 8 9]]
8
[2 5 8]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
x2 = np.array ([[1,2],[3,4],[5,6]])
x2.shape

(3, 2)

In [ ]:
x2.T
print(x2)
x2.shape

[[1 2]
 [3 4]
 [5 6]]


(3, 2)

In [3]:
a1 = np.array(([1,2,3,4],[5,6,7,8],[9,10,11,12]))
print(a1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [4]:
slice_a1 = a1[0:2,1:3] # a1[Row,column] 0:2 -> row 0 till row 1(2-1)
print(slice_a1)

[[2 3]
 [6 7]]
