In [1]:
import numpy as np
a = np.array(([1,2],[3,4],[5,6]))
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [2]:
bool_idx = a>2
print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [3]:
print(a[bool_idx])

[3 4 5 6]


In [4]:
print(a[a>2])

[3 4 5 6]


In [5]:
print(a[a> 4])

[5 6]




#Test condition

np.where(condition,value_if_true,value_if_false)



In [6]:
b = np.where(a>2,a,-1)
print(b)

[[-1 -1]
 [ 3  4]
 [ 5  6]]


In [7]:
temps = np.array([28,32,35,30,25,27,22,33,36,29,39,26,24])
label = np.where(temps > 30 , "Hot" , "Cold")
print(label)

['Cold' 'Hot' 'Hot' 'Cold' 'Cold' 'Cold' 'Cold' 'Hot' 'Hot' 'Cold' 'Hot'
 'Cold' 'Cold']


In [9]:
marks = np.array([35,50,67,78,88,45])
result = np.where(marks > 60 , "Pass", "Fail")
print(result)

['Fail' 'Fail' 'Pass' 'Pass' 'Pass' 'Fail']


In [10]:
marks = np.array([[45,33,67],[78,89,81],[39,50,48],[61,73,63]])
result = np.where (marks > 50 ,"Pass" ,"Fail")
print(result)

[['Fail' 'Fail' 'Pass']
 ['Pass' 'Pass' 'Pass']
 ['Fail' 'Fail' 'Fail']
 ['Pass' 'Pass' 'Pass']]


#Fancy Indexing - > To print multiple index at one time

In [12]:
a = np.array([10,20,30,40,50,60,70])
print(a[5])
b = a[[1,3,5]]
print(b)

60
[20 40 60]


#np.argwhere(): Get indices of **True** values



In [14]:
even = np.argwhere(a%3 == 0)
print(even)
even.shape

[[2]
 [5]]


(2, 1)

#Flatten -> convert 2D to 1D

In [18]:
c = even.flatten()
print(c)
c.shape

[2 5]


(2,)